dist: precise
## Use docker image for speed
## When pandoc whitelisted:
##  https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
## Issue here:
##  https://github.com/travis-ci/apt-package-whitelist/issues/3762
#sudo: false
#group: beta
#
# C includes autotools and make by default
language: c
#
# Extra packages
addons:
  apt:
    packages:
    - gnupg
    - help2man
    - fakeroot
#
# Setup environment
before_install:
 # Decrypt our private files for CI use only
 - eval "$(ssh-agent -s)"
 - ./.travis/decrypt-if-have-key df4daddc19fe
 - export KEYSERVER=pool.sks-keyservers.net
#
# Run
before_script:
 # Download keys - builds of tags check for a recognised signature
 - ./packaging/gpg-recv-key phil@firehol.org "0762 9FF7 89EA 6156 012F  9F50 C406 9602 1359 9237"
 - ./packaging/gpg-recv-key costa@tsaousis.gr "4DFF 624A E564 3B51 2872  1F40 29CA 3358 89B9 A863"
 # Run the commit hooks in case the developer didn't
 - git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 | ./packaging/check-files -
script:
 - fakeroot ./packaging/git-build && ./configure && make check
#
# Deploy as required
after_success:
  - for i in *.tar.*; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha; done
  - ./.travis/deploy-if-have-key iprange
deploy:
  # Upload results to GitHub (tag only)
  - provider: releases
    api_key:
      secure: 0jehBAOuMmI+CqjYP4Mf7Kmh3wa3kVBeWLqUr3aFXyYsOH1Hp5Qnv7woY3Kj0PSPf7l3oEFxERJB5mQCsg8glJsHiFyFmc9xWMILT7Pq5OrAcg2vWUwJMYW/UqOEk0F4d7yCXneMwXcITYPEoMZQDU0QuXEzA2IKwpt0mMv/U3EAC0LwyyVyvvHXhJ++WrceuYoC1Nbjd6CyTKfllJi2c1fEIXgtJCA/Ny2qDr1lHWcP60WxKHDuVwNoqf/7C4ahQb1lAV5hIEUz6LHLM3aLWw8L1e+UzTpEKAtwTlTcTliJ40ATTqHSRodJs25yRNV9CL7xJ9/K+bbswTYBw2kLkhZ4ufPr9WxhIFN/GAIG75uRnc3DS7dkBJjF8GwD21+X+QS0ryk7JMAAq8d/SdZopsl6kwl7gf5C9r7OAq25JgSUOdTvy+GGoz2/jEKi7rmgkTORW2vmzKUBMS/BIIJIpyoOuJOXfMhq9aR3TSaak4hrC4CHdOuoaeer6X6+/HQcxcOhx3OpulzVs8aEAKGc1sHkYIOjsBHyd2le8JqtquNVZrdHoMB3WuuQNuVv3gYkLHr1UnkQQ+6Bgbf55mkp7lj7rzhWhFtbu5AfwL7EenJwYYxYJ1NzLcrpr7GaGy2NCxFgJr927425Q1hITWuK9ocsRid+GVkkjyK5EcaGp2U=
    skip_cleanup: true
    file_glob: true
    file: "iprange*.tar.*"
    on:
      repo: firehol/iprange
      tags: true
